name: "GitHub Actions Deploy Bot"

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: "14"
      - name: Install dependencies
        run: cd packages/docs-ui && npm install
      - name: Build
        run: npm run docs:build
      - name: Show Log
        run: ls
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
